api_platform:
    swagger:
        api_keys:
            # overridden in OpenApiFactoryDecorator for Bearer scheme
            access_token:
                name: Authorization
                type: header
