framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - App\Messenger\LoggerMiddleware

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_transaction:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                    delay: 200
                options:
                    exchange:
                        name: messages_transaction
                    queues:
                        messages_transaction: ~

            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
            'App\Message\TransactionMessage': async_transaction
