version: '3.4'

services:
    php:
        image: barlito/youl-coin-api:${TAG}
        environment:
            APP_ENV: prod
            DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@youl_coin_db:5432/youl_coin?serverVersion=13&charset=utf8"
            MESSENGER_TRANSPORT_DSN: "amqp://${AMQP_USER}:${AMQP_PASS}@youl_coin_rabbitmq:5672/%2f/messages"
            DISCORD_DSN: "${DISCORD_DSN}"
            OAUTH_DISCORD_CLIENT_ID: "${OAUTH_DISCORD_CLIENT_ID}"
            OAUTH_DISCORD_CLIENT_SECRET: "${OAUTH_DISCORD_CLIENT_SECRET}"
        logging:
            driver: loki
            options:
                loki-url: "http://176.31.100.99:3100/loki/api/v1/push"
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin.loadbalancer.server.port=80

                - traefik.http.routers.youlcoin.rule=Host(`yc.barlito.fr`)
                - traefik.http.routers.youlcoin.entrypoints=http
                - traefik.http.routers.youlcoin.middlewares=tls-redirectscheme

                - traefik.http.routers.youlcoin-secure.rule=Host(`yc.barlito.fr`)
                - traefik.http.routers.youlcoin-secure.entrypoints=https
                - traefik.http.routers.youlcoin-secure.tls=true
                - traefik.http.routers.youlcoin-secure.tls.certresolver=letsencrypt
        networks:
            - traefik_traefik_proxy

    db:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - traefik_traefik_proxy
        volumes:
            - youl_coin_db:/var/lib/postgresql/data:rw
        ports:
            - target: 5432
              published: 5432
              protocol: tcp
              mode: host

    adminer:
        image: adminer
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin_adminer.loadbalancer.server.port=8080

                - traefik.http.routers.youlcoin_adminer.rule=Host(`yc-adminer.barlito.fr`)
                - traefik.http.routers.youlcoin_adminer.entrypoints=http
                - traefik.http.routers.youlcoin_adminer.middlewares=tls-redirectscheme

                - traefik.http.routers.youlcoin_adminer-secure.rule=Host(`yc-adminer.barlito.fr`)
                - traefik.http.routers.youlcoin_adminer-secure.entrypoints=https
                - traefik.http.routers.youlcoin_adminer-secure.tls=true
                - traefik.http.routers.youlcoin_adminer-secure.tls.certresolver=letsencrypt
        networks:
            - traefik_traefik_proxy

    rabbitmq:
        image: rabbitmq:3-management
        hostname: yc-rabbitmq
        volumes:
            - yc_exchange_rabbit_mq_data:/var/lib/rabbitmq:rw
        environment:
            RABBITMQ_DEFAULT_USER: ${AMQP_USER}
            RABBITMQ_DEFAULT_PASS: ${AMQP_PASS}
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin_rabbitmq.loadbalancer.server.port=15672

                - traefik.http.routers.youlcoin_rabbitmq.rule=Host(`yc-rabbitmq.barlito.fr`)
                - traefik.http.routers.youlcoin_rabbitmq.entrypoints=http
                - traefik.http.routers.youlcoin_rabbitmq.middlewares=tls-redirectscheme

                - traefik.http.routers.youlcoin_rabbitmq-secure.rule=Host(`yc-rabbitmq.barlito.fr`)
                - traefik.http.routers.youlcoin_rabbitmq-secure.entrypoints=https
                - traefik.http.routers.youlcoin_rabbitmq-secure.tls=true
                - traefik.http.routers.youlcoin_rabbitmq-secure.tls.certresolver=letsencrypt
        networks:
            - traefik_traefik_proxy

volumes:
    youl_coin_db:
    yc_exchange_rabbit_mq_data:

networks:
    traefik_traefik_proxy:
        external: true
