version: '3.4'

services:
    php:
        image: yc-php
        build:
            context: .
            dockerfile: .docker/Dockerfile
        environment:
            SERVER_NAME: ":80"
        volumes:
            - ./:/app
            - ./.docker/supervisor.d:/etc/supervisor
            - ./.docker/franken/Caddyfile:/etc/caddy/Caddyfile
            - ~/.composer:/root/.composer:delegated
            - yc_caddy_data:/data
            - yc_caddy_config:/config
        tty: true
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin.loadbalancer.server.port=80

                - traefik.http.routers.youlcoin.rule=Host(`yc.local.barlito.fr`)
                - traefik.http.routers.youlcoin.entrypoints=http
#                - traefik.http.routers.youlcoin.middlewares=tls-redirectscheme

                - traefik.http.routers.youlcoin-secure.rule=Host(`yc.local.barlito.fr`)
                - traefik.http.routers.youlcoin-secure.entrypoints=https
                - traefik.http.routers.youlcoin-secure.tls=true
        networks:
            - yc_api_internal
            - traefik_traefik_proxy

    db:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: root
        volumes:
            - yc_api_db_data:/var/lib/postgresql/data:rw
        networks:
            - yc_api_internal

    adminer:
        image: adminer
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin_adminer.loadbalancer.server.port=8080

                - traefik.http.routers.youlcoin_adminer.rule=Host(`yc-adminer.local.barlito.fr`)
                - traefik.http.routers.youlcoin_adminer.entrypoints=http

                - traefik.http.routers.youlcoin_adminer-secure.rule=Host(`yc-adminer.local.barlito.fr`)
                - traefik.http.routers.youlcoin_adminer-secure.entrypoints=https
                - traefik.http.routers.youlcoin_adminer-secure.tls=true
        networks:
            - yc_api_internal
            - traefik_traefik_proxy

    rabbitmq:
        image: rabbitmq:3-management
        hostname: yc-rabbitmq
        volumes:
            - yc_exchange_rabbit_mq_data:/var/lib/rabbitmq:rw
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin_rabbitmq.loadbalancer.server.port=15672

                - traefik.http.routers.youlcoin_rabbitmq.rule=Host(`yc-rabbitmq.local.barlito.fr`)
                - traefik.http.routers.youlcoin_rabbitmq.entrypoints=http

                - traefik.http.routers.youlcoin_rabbitmq-secure.rule=Host(`yc-rabbitmq.local.barlito.fr`)
                - traefik.http.routers.youlcoin_rabbitmq-secure.entrypoints=https
                - traefik.http.routers.youlcoin_rabbitmq-secure.tls=true
        networks:
            - yc_api_internal
            - traefik_traefik_proxy

volumes:
    yc_api_db_data:
    yc_exchange_rabbit_mq_data:
    yc_caddy_data:
    yc_caddy_config:

networks:
    traefik_traefik_proxy:
        external: true
    yc_api_internal:
        driver: overlay
