version: '3.4'

services:
    nginx:
        # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#customization
        image: webdevops/php-nginx-dev:8.1
        volumes:
            - ./app:/app
            - ./.docker/nginx/conf.d/default.conf:/opt/docker/etc/nginx/vhost.conf
#            todo add this config file under ./.docker
            - ./.docker/supervisor.d/messenger-worker.conf:/opt/docker/etc/supervisor.d/messenger-worker.conf
        working_dir: /app
        environment:
            # PHP config
            # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#environment-variables
            PHP_DATE_TIMEZONE: "Europe/Paris"
            PHP_DISPLAY_ERRORS: "on"
            PHP_MEMORY_LIMIT: 512M
            PHP_MAX_EXECUTION_TIME: 7200
            PHP_REQUEST_TERMINATE_TIMEOUT: 7200
            PHP_POST_MAX_SIZE: 50M
            PHP_UPLOAD_MAX_FILESIZE: 50M
            PHP_OPCACHE_REVALIDATE_FREQ: 0
            php.xdebug.var_display_max_depth: 10
            php.xdebug.var_display_max_data: 2048
            XDEBUG_MODE: coverage
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin.loadbalancer.server.port=80

                - traefik.http.routers.youlcoin.rule=Host(`yc.local.barlito.fr`)
                - traefik.http.routers.youlcoin.entrypoints=http
#                - traefik.http.routers.youlcoin.middlewares=tls-redirectscheme

                - traefik.http.routers.youlcoin-secure.rule=Host(`yc.local.barlito.fr`)
                - traefik.http.routers.youlcoin-secure.entrypoints=https
                - traefik.http.routers.youlcoin-secure.tls=true
        networks:
            - yc_api_internal
            - traefik_traefik_proxy

    db:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: root
        volumes:
            - yc_api_db_data:/var/lib/postgresql/data:rw
        networks:
            - yc_api_internal

    adminer:
        image: adminer
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin_adminer.loadbalancer.server.port=8080

                - traefik.http.routers.youlcoin_adminer.rule=Host(`yc-adminer.local.barlito.fr`)
                - traefik.http.routers.youlcoin_adminer.entrypoints=http

                - traefik.http.routers.youlcoin_adminer-secure.rule=Host(`yc-adminer.local.barlito.fr`)
                - traefik.http.routers.youlcoin_adminer-secure.entrypoints=https
                - traefik.http.routers.youlcoin_adminer-secure.tls=true
        networks:
            - yc_api_internal
            - traefik_traefik_proxy

    rabbitmq:
        image: rabbitmq:3-management
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.youlcoin_rabbitmq.loadbalancer.server.port=15672

                - traefik.http.routers.youlcoin_rabbitmq.rule=Host(`yc-rabbitmq.local.barlito.fr`)
                - traefik.http.routers.youlcoin_rabbitmq.entrypoints=http

                - traefik.http.routers.youlcoin_rabbitmq-secure.rule=Host(`yc-rabbitmq.local.barlito.fr`)
                - traefik.http.routers.youlcoin_rabbitmq-secure.entrypoints=https
                - traefik.http.routers.youlcoin_rabbitmq-secure.tls=true
        networks:
            - yc_api_internal
            - traefik_traefik_proxy

volumes:
    yc_api_db_data:

networks:
    traefik_traefik_proxy:
        external: true
    yc_api_internal:
        driver: overlay
