services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Functional\:
        resource: '../tests/Functional/*'

    App\Tests\Unit\:
        resource: '../tests/Unit/*'

    # Services

    App\Tests\Behat\EntityManagerContext:
        $entityNamespace: App\Entity

    App\Tests\Behat\Mock\LoggerMock:
        decorates: Psr\Log\LoggerInterface
        arguments:
            - '@App\Tests\Behat\Mock\LoggerMock.inner'

    App\Tests\Behat\Mock\TransactionNotifierMock:
        decorates: App\Service\Notifier\Transaction\Abstract\Interface\TransactionNotifierInterface
        arguments:
            - '@App\Tests\Behat\Mock\TransactionNotifierMock.inner'