version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: mkdir -p var/data
      - run: make-deploy
      - run: make check_style
      - run: make phpunit
      - run: make undeploy
