monolog:
    handlers:
        main:
            type: stream
            path: php://stdout
            level: info
            channels: [ "!doctrine", "!event", "!request", "!security" ]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
