framework:
    messenger:
#        failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - App\Service\Messenger\Middleware\LoggerMiddleware

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_transaction:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Service\Messenger\Serializer\TransactionMessageSerializer
                retry_strategy:
                    max_retries: 0
                options:
                    queues:
                        messages_transaction: ~

#            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
            'App\Message\TransactionMessage': async_transaction
