framework:
    messenger:
#        failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_transaction
                    - App\Service\Messenger\Middleware\LoggerMiddleware

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_transaction:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Service\Messenger\Serializer\TransactionMessageSerializer
                retry_strategy:
                    max_retries: 0
                options:
                    persistent: true
                    exchange:
                        name: transaction_exchange
                    queues:
                        messages_transaction: ~

            transaction_notification:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Service\Messenger\Serializer\TransactionNotificationSerializer
                options:
                    persistent: true
                    exchange:
                        name: transaction_notification_exchange
                    queues: []

        routing:
            # Route your messages to the transports
            'App\Message\TransactionMessage': async_transaction
            'App\Entity\Transaction': transaction_notification
