name: App Setup re-usable workflow

on: workflow_call

jobs:
  code_quality:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Deploy stack
        run: make docker.deploy.ci

      - name: Check app works well
        run: "curl -I http://localhost:8081/ | grep -q 'Server: nginx'"

      - name: Setup github token
        run: make composer.command args="config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}"