name: Release Workflow

on:
  release:
    types: [published]

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Todo deploy stack and run composer install with optimized autoloader
      - name: Deploy stack
        run: make deploy.ci args=${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/youl-coin-api:$GITHUB_REF_NAME .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_READ_WRITE_DELETE_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/youl-coin-api:$GITHUB_REF_NAME