name: Release Workflow

on: workflow_dispatch

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Build Docker Image
        run: docker build -t youl-coin-api:$GITHUB_REF_NAME .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_READ_WRITE_DELETE_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push youl-coin-api:$GITHUB_REF_NAME