name: Release Workflow

on:
  release:
    types: [published]

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Build Docker Image
        run: docker build -t latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/youl-coin-api:$GITHUB_REF_NAME .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_READ_WRITE_DELETE_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push --all-tags ${{ secrets.DOCKER_HUB_USERNAME }}/youl-coin-api
