name: Starter workflow

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  code_quality:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Deploy stack
        run: make deploy.ci args=${{ secrets.GITHUB_TOKEN }}

      - name: Run php cs fixer
        run: make cs_fixer.dry_run

      - name: Run php cs
        run: make phpcs

      - name: Run phpmd
        run: make phpmd

      - name: Undeploy stack
        run: make docker.undeploy.ci